# The Numpy array Object

# Numpy Arrays

python objects:
    1. high level number objects: integers,floating point

In [2]:
import numpy as np
a = np.array([0,1,2,3,4])
print(a)

print(np.arange(10))
print(np.arange(5,10))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


# why it is useful:
Memory-efficient container that provides fast numerical operations

In [3]:
#python list
L = range(1000)
%timeit [i**2 for i in L]

352 μs ± 103 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
#with numpy
a = np.arange(1000)
%timeit a**2

5.01 μs ± 1.32 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# 1. Creating arrays

In [9]:
# Manual  construction
#1D
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [8]:
#print dimensions
a.ndim

1

In [10]:
#shape
a.shape

(5,)

In [12]:
#length
len(a)

5

In [ ]:
# 2D, 3D....

b = np.array([[0,1,2],[3,4,5]])
print(b)

print(b.ndim)
print(b.shape)
print(len(b))  # returns the size of first dimension

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2


In [17]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(c)

print(c.ndim)
print(c.shape)
print(len(c))  # returns the size of first dimension

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
2


In [18]:
#using arange function

a  = np.arange(10) # 0....n-1
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1,10,2) #start, end(exclusive),step
b

array([1])

In [23]:
# using linspace

a = np.linspace(0,1,6) #start ,end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [29]:
#common array
a = np.ones((3,4))
b = np.zeros((3,4))
a,b

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [ ]:
c = np.eye(3)  #Return a 2D array with ones on the diagonal
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
c = np.eye(3,2)  # 3 is no of rows , 2 is no of diagonal
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [32]:
a = np.diag([1,2,3,4]) # construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
np.diag(a)  #Extract diagonal

array([1, 2, 3, 4])

In [40]:
#create array using random

#Create an array of the given shape and populate it with random
a = np.random.rand(4)
b = np.random.rand(5)
c = np.random.rand(3)
a,b,c



(array([0.60347777, 0.71565922, 0.98529906, 0.47389679]),
 array([0.05531976, 0.99317064, 0.18167306, 0.72382679, 0.69299007]),
 array([0.60698935, 0.36768927, 0.20842994]))

In [41]:
a = np.random.randn(4) # Return a sample(or smaples) from the
a

array([-1.98426869, -0.83238065,  1.10419509, -0.37922653])

In [42]:
a = np.arange(10)
a.dtype

dtype('int64')

In [43]:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
a = np.zeros((3,3))
print(a)
a.dtype


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [45]:
d = np.array([1+2j,2+4j])   #complex datatype
print(d.dtype)

complex128


In [46]:
b = np.array([True,False,True,False]) # Boolean datatype
print(b.dtype)

bool


In [47]:
s = np.array(['Ram',"Robert",'Rahim'])
s.dtype

dtype('<U6')

In [ ]:
a = np.arange(10)
print(a[5])  #0-indexing

5


In [ ]:
# For multi dimensional array , indexes are tuples of integer

a = np.diag([1,2,3,4])
print(a[2,2])

3


In [51]:
a[2,1] = 5 # assigning value 
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 5, 3, 0],
       [0, 0, 0, 4]])

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [55]:
# we can also combine assignment and slicing

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [57]:
b = np.arange(5)
a[5:] = b[::-1] #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [62]:
np.shares_memory(a,b)

True

In [63]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [64]:
np.shares_memory(a,b)

True

In [ ]:
a # eventhrogh  we modified b, it updated 'a' because both share the same memory location

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [66]:
a =  np.arange(10)
c = a[::2].copy()  #force a copy
c

array([0, 2, 4, 6, 8])

In [67]:
np.shares_memory(a,c)

False

In [69]:
c[0] = 20
a,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([20,  2,  4,  6,  8]))