# Numpy 

In [3]:
import numpy as np
a = np.array([0,1,2,3,4])
print(a)

print(np.arange(10))
print(np.arange(5,10))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


# why it is useful:
Memory-efficient container that provides fast numerical operations

In [ ]:
#python list
L = range(1000)
%timeit [i**2 for i in L]

143 μs ± 1.92 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
#with numpy
a = np.arange(1000)
%timeit a**2

2.63 μs ± 37.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
