# The Numpy array Object

# Numpy Arrays

python objects:
    1. high level number objects: integers,floating point

In [2]:
import numpy as np
a = np.array([0,1,2,3,4])
print(a)

print(np.arange(10))
print(np.arange(5,10))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


# why it is useful:
Memory-efficient container that provides fast numerical operations

In [3]:
#python list
L = range(1000)
%timeit [i**2 for i in L]

165 μs ± 16.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
#with numpy
a = np.arange(1000)
%timeit a**2

4.56 μs ± 726 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# 1. Creating arrays

In [5]:
# Manual  construction
#1D
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [6]:
#print dimensions
a.ndim

1

In [7]:
#shape
a.shape

(5,)

In [8]:
#length
len(a)

5

In [9]:
# 2D, 3D....

b = np.array([[0,1,2],[3,4,5]])
print(b)

print(b.ndim)
print(b.shape)
print(len(b))  # returns the size of first dimension

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2


In [10]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(c)

print(c.ndim)
print(c.shape)
print(len(c))  # returns the size of first dimension

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
2


In [11]:
#using arange function

a  = np.arange(10) # 0....n-1
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(1,10,2) #start, end(exclusive),step
b

array([1, 3, 5, 7, 9])

In [13]:
# using linspace

a = np.linspace(0,1,6) #start ,end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
#common array
a = np.ones((3,4))
b = np.zeros((3,4))
a,b

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [15]:
c = np.eye(3)  #Return a 2D array with ones on the diagonal
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
c = np.eye(3,2)  # 3 is no of rows , 2 is no of diagonal
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [17]:
a = np.diag([1,2,3,4]) # construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
np.diag(a)  #Extract diagonal

array([1, 2, 3, 4])

In [19]:
#create array using random

#Create an array of the given shape and populate it with random
a = np.random.rand(4)
b = np.random.rand(5)
c = np.random.rand(3)
a,b,c



(array([0.06289394, 0.22448759, 0.94136388, 0.093859  ]),
 array([0.40238197, 0.78665686, 0.31069218, 0.21788492, 0.54252311]),
 array([0.8633767 , 0.6893462 , 0.80557448]))

In [20]:
a = np.random.randn(4) # Return a sample(or smaples) from the
a

array([ 0.87463403,  1.73768005, -0.39801707, -0.0530287 ])

In [21]:
a = np.arange(10)
a.dtype

dtype('int64')

In [22]:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
a = np.zeros((3,3))
print(a)
a.dtype


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [24]:
d = np.array([1+2j,2+4j])   #complex datatype
print(d.dtype)

complex128


In [25]:
b = np.array([True,False,True,False]) # Boolean datatype
print(b.dtype)

bool


In [26]:
s = np.array(['Ram',"Robert",'Rahim'])
s.dtype

dtype('<U6')

In [27]:
a = np.arange(10)
print(a[5])  #0-indexing

5


In [28]:
# For multi dimensional array , indexes are tuples of integer

a = np.diag([1,2,3,4])
print(a[2,2])

3


In [29]:
a[2,1] = 5 # assigning value 
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 5, 3, 0],
       [0, 0, 0, 4]])

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [32]:
# we can also combine assignment and slicing

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [33]:
b = np.arange(5)
a[5:] = b[::-1] #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [36]:
np.shares_memory(a,b)

True

In [37]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [38]:
np.shares_memory(a,b)

True

In [39]:
a # eventhrogh  we modified b, it updated 'a' because both share the same memory location

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [40]:
a =  np.arange(10)
c = a[::2].copy()  #force a copy
c

array([0, 2, 4, 6, 8])

In [41]:
np.shares_memory(a,c)

False

In [42]:
c[0] = 20
a,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([20,  2,  4,  6,  8]))

# Fancy Indexing

In [43]:
a = np.random.randint(0,20,15)
a

array([ 6,  2, 14,  5,  9,  7, 16, 12, 14,  4, 17,  1, 17,  1,  6],
      dtype=int32)

In [45]:
mask = (a%2==0)
print(mask)

[ True  True  True False False False  True  True  True  True False False
 False False  True]


In [46]:
extract_from_a = a[mask]
extract_from_a

array([ 6,  2, 14, 16, 12, 14,  4,  6], dtype=int32)

In [47]:
a[mask] = -1
a

array([-1, -1, -1,  5,  9,  7, -1, -1, -1, -1, 17,  1, 17,  1, -1],
      dtype=int32)

In [51]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
# indexing can be done with an array of integers 
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [56]:
a[[9,7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

In [ ]:
s = np.array(['Ram',"Anand",'Tom'])
s.dtype

# U5 ( Unicode string with max string of length 5)

dtype('<U5')