# Elementwise Operations
1. Basic Operations
With scalars
Day: 28
Date: 03/12/2025
Day: Wednesday

In [1]:
import numpy as np

In [22]:
# Load data in numpy array object
data = np.loadtxt("populations.txt")
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [3]:
year, hares, lynxes, carrots = data.T # Columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [4]:
populations = data[:,1:]
print(populations)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [5]:
# Sample standard deviation
print(populations.std(axis=0))

[20897.90645809 16254.59153691  3322.50622558]


In [6]:
# Which species has the highest population each year?
print(np.argmax(populations, axis=1))

[2 2 0 0 1 1 2 2 2 2 2 2 0 0 0 1 2 2 2 2 2]


# Broadcasting

In [7]:
a = np.tile(np.arange(0, 40, 10), (3, 1)) # Here 3 denotes that reapeat 3 times
print(a)
print("*****************")
a = a.T # Transpose the matrix
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*****************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [8]:
print(a.shape) # Find shape

b = np.array([0,1,2])
print(b)

a + b

(4, 3)
[0 1 2]


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [9]:
a = np.arange(0,40,10)
print(a.shape)

a = a[:, np.newaxis] # Adds a new axis -> 2D Array
print(a.shape)
print(a)

(4,)
(4, 1)
[[ 0]
 [10]
 [20]
 [30]]


In [10]:
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# Array Shape Manipilation
Flattening

In [11]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ravel()) #Returns a contiguous flattened array. A 1-D Array.

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [12]:
print(a.T) # Transpose

[[1 4]
 [2 5]
 [3 6]]


In [13]:
print(a.T.ravel())

[1 4 2 5 3 6]


Reshaping

In [14]:
# The inverse operation to flattening
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [15]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [16]:
b = b.reshape((2,3))
print(b.shape)
print(b)

b[1,1] = 10
print(b)
# Here value of a is also changing when we change b. So they are pointing to the same memory location.
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 10  6]]
[[ 1  2  3]
 [ 4 10  6]]


In [17]:
a = np.arange(4)
a.resize((8,))
print(a)

[0 1 2 3 0 0 0 0]


In [18]:
b = a
a.resize((4,)) # It will give error

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

Sorting Data

In [ ]:
# Sorting along an axis
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a, axis=1)
print(b)

[[4 5 6]
 [2 2 3]]


In [ ]:
# In-place sort
a.sort(axis=1)
print(a)

[[4 5 6]
 [2 2 3]]


In [ ]:
# Sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a) # Give index
print(j)

[2 3 1 0]


In [ ]:
print(a[j])

[1 2 3 4]
