In [3]:
import numpy as np

# Elementwise Operations



1. Basic Operation

with scalars

In [4]:
a = np.array([1,2,3,4]) 
a+1

array([2, 3, 4, 5])

In [5]:
a**2

array([ 1,  4,  9, 16])

All arithmetic operates elementwise

In [8]:
b = np.ones(4) +1
print(a)
print(b)

a-b

[1 2 3 4]
[2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.])

In [9]:
a * b

array([2., 4., 6., 8.])

In [11]:
# matrix multiplication

c = np.diag([1,2,3,4])

print(c*c)
print("********************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


comparisions

In [14]:
a = np.array([1,2,3,4])
b = np.array([5,2,3,6])

a==b

array([False,  True,  True, False])

In [15]:
a>b

array([False, False, False, False])

In [16]:
# array-wise comparisions
a = np.array([1,2,3,4])
b = np.array([5,2,3,7])
c = np.array([1,2,3,4])

np.array_equal(a,b)


False

In [17]:
np.array_equal(a,c)

True

Logical Operations

In [19]:
a = np.array([1,1,0,1],dtype=bool)
b = np.array([1,0,1,1],dtype=bool)

print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))
print(np.logical_xor(a,b))



[ True  True  True  True]
[ True False False  True]
[False False  True False]
[ True  True  True  True]


In [20]:
a = np.array([1,2,0,1],dtype=bool)
a

array([ True,  True, False,  True])