In [3]:
import numpy as np

# Elementwise Operations



1. Basic Operation

with scalars

In [4]:
a = np.array([1,2,3,4]) 
a+1

array([2, 3, 4, 5])

In [5]:
a**2

array([ 1,  4,  9, 16])

All arithmetic operates elementwise

In [8]:
b = np.ones(4) +1
print(a)
print(b)

a-b

[1 2 3 4]
[2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.])

In [9]:
a * b

array([2., 4., 6., 8.])

In [11]:
# matrix multiplication

c = np.diag([1,2,3,4])

print(c*c)
print("********************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


comparisions

In [14]:
a = np.array([1,2,3,4])
b = np.array([5,2,3,6])

a==b

array([False,  True,  True, False])

In [15]:
a>b

array([False, False, False, False])

In [16]:
# array-wise comparisions
a = np.array([1,2,3,4])
b = np.array([5,2,3,7])
c = np.array([1,2,3,4])

np.array_equal(a,b)


False

In [17]:
np.array_equal(a,c)

True

Logical Operations

In [19]:
a = np.array([1,1,0,1],dtype=bool)
b = np.array([1,0,1,1],dtype=bool)

print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))
print(np.logical_xor(a,b))



[ True  True  True  True]
[ True False False  True]
[False False  True False]
[ True  True  True  True]


In [20]:
a = np.array([1,2,0,1],dtype=bool)
a

array([ True,  True, False,  True])

In [22]:
a = np.arange(5)
print(a)
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))

[0 1 2 3 4]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]
[      -inf 0.         0.69314718 1.09861229 1.38629436]


C:\Users\pcc\AppData\Local\Temp\ipykernel_11416\2255193552.py:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [23]:
np.exp(a) #evaluate e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
a = np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [29]:
# Computing Sum

x = np.array([1,2,3,4])
print(np.sum(x))

10


In [31]:
# Sum by Rows and by columns

x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [34]:
x.sum(axis=0)  # columns first dimension

array([3, 3])

In [36]:
x.sum(axis=1)  # row ( second dimension)

array([2, 4])

Order Reductions

In [37]:
print(x.min())
print(x.max())

1
2


In [38]:
x.argmin()  # index of minimum element

np.int64(0)

In [39]:
x.argmax()  # index of maximum element


np.int64(2)

Logical Operations

In [40]:
np.all([True,True,False])

np.False_

In [41]:
np.any([True,True,False])

np.True_

In [43]:
a = np.zeros((50,50))
np.any(a!=0)

np.False_

In [44]:
np.all(a==a)

np.True_

In [48]:
a = np.array([1,2,3,4])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
print(a<=b)
print(b<=c)
print((a<=b) & (b<=c))
print(((a<=b) & (b<=c)).all())


[ True  True  True False]
[ True  True  True  True]
[ True  True  True False]
False


In [49]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

np.float64(1.75)

In [50]:
np.median(x)

np.float64(1.5)

In [51]:
np.median(y,axis=-1) # last axis

array([2., 5.])

In [52]:
x.std()  # full population standard deviation

np.float64(0.82915619758885)